name: Main Release or Pull Request
run-name: >-
  ${{ github.event_name == 'push'
    && format('Creating a Release by {0} with tag {1}', github.actor, github.ref_name)
    || format('Pull Request to Main by {0}', github.actor) }}
on: 
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags:
      - 'v*'
  

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

jobs:
  createRelease:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.tagPush }}
      output2: ${{ steps.step1.outputs.success }}
    steps:
      - name: IsRelease
        run: echo "tagPush=false" >> "$GITHUB_OUTPUT"
        
      - name: CreateRelease
        if: ${{ github.event_name == 'push' }}
        id: step1
        run: |
          if [[ ${{ github.ref_name }} == v* ]]; then
            echo "tagPush=true" >> "$GITHUB_OUTPUT"
            echo "success=false" >> "$GITHUB_OUTPUT"
          else
            echo "No process needed"
            exit 0
          fi
          gh release create ${{ github.ref_name }} --notes-from-tag --title ${{ github.ref_name }} --verify-tag
          echo "success=true" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ${{ matrix.os }}
    needs: createRelease
    if: ${{ always() && !cancelled() && ( github.event_name == 'pull_request' || ( github.event_name == 'push' && github.ref_name == 'v*'' ) ) }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest]
        build_type: [Debug, Release]
        c_compiler: [clang]
        include:
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: Install Requirements
      run: |
        sudo bash requirements.sh

    - name: Set Up VCPkg
      id: vcpkg-setup
      run: |
        cd ${{ github.workspace }}/..
        git clone https://github.com/microsoft/vcpkg.git
        cd ./vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
        ./vcpkg integrate bash
        ./vcpkg install gtest
        echo "VCPKG_ROOT=${{ github.workspace }}/../vcpkg/" >> "$GITHUB_OUTPUT"

    - name: Build Project
      env:
        VCPKG_ROOT: ${{ steps.vcpkg-setup.outputs.VCPKG_ROOT }}
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        mkdir ${{ matrix.build_type }}
        cd ${{ matrix.build_type }}
        cmake ../.. -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++
        ninja
    
    - name: Run Hello World tests
      run: |
        ./build/${{ matrix.build_type}}/test/hello_world_test
        
    - name: Upload Release Artifacts
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ needs.createRelease.outputs.output1 == 'true' }}
      run: |
        echo ${{ needs.createRelease.outputs.output2 }}
        if [ ${{ needs.createRelease.outputs.output2 }} = "false" ]; then
          echo "False"
          exit 1
        else
          echo "True"
        fi
        gh release upload ${{ github.ref_name }} ./build/${{ matrix.build_type}}/hello_world#hello_world-${{ matrix.build_type }}